/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'richo' at '4/3/16 7:45 PM' with Gradle 2.12
 *
 * @author richo, @date 4/3/16 7:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
